typography_spectrum: 0.7285079098549109
content_rating:
  adult: false
color:
  brandColors:
    - '#B9B6AF'
    - '#242321'
    - '#9E9085'
    - '#41403E'
    - '#757170'
  brandStrength: 0.2526392480312376
  lightness: 0.06678831850879337
  saturation: 0.4916542467136526
  rhythmicContrast: 0.4063281369575364
github: true
opengraph:
  image: null
  type: null
  appId: ''
layout_spectrum: 0.7369670959924449
analytics:
  google: UA-84855412-1
  facebook: null
  twitter: ''
author:
  name: PHILLIP JOHNSON
  email: philjo_1005@yahoo.co.uk
  url: 'https://phillipjohnson.org.uk'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8540bd32-0c75-4775-87f5-38c2a0577a31.jpg
name: Daniel Murray Art
url: 'https://danielmurrayartist.co.uk'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Daniel Murray Art
    id: 14dd2040-420d-44cb-80e4-f20cbb0cea24
    type: content
  - name: Portraits
    id: 02f6c521-4dbe-45dc-9ad8-53e61e90bba1
    type: content
  - name: Other Work
    id: dfb034bf-d30c-4b5e-83d3-6baec55403f3
    type: content
  - name: About
    id: 4aea76a4-a258-467d-833c-12e9d7fcc7e8
    type: content
  - name: Contact
    id: ed616755-5e27-46a9-b1b4-15324c68d403
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4e1bf45b-9001-4443-8a41-43adb4b13e88.ico
title: Daniel Murray Artist
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/540a327f-74ef-4cac-9719-1d19943c5c6e.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/540a327f-74ef-4cac-9719-1d19943c5c6e.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Visual artist working in the Highlands
purpose:
  - type: external
    url: 'https://www.facebook.com/Dan-Murray-Artist-197596477105627/'
    label: Facebook
